from __future__ import annotations

from schedule_policy import ScheduleMode

STATUS_SCHEDULE_MIN_MINUTES = 5
STATUS_SCHEDULE_MAX_MINUTES = 1440
STATUS_SCHEDULE_MAX_WINDOWS = 24
STATUS_AUTOPOST_TICK_SECONDS = 30
STATUS_AUTOPOST_RETRY_SECONDS = 60
STATUS_SCHEDULE_MODE_FIXED: ScheduleMode = "fixed"
STATUS_SCHEDULE_MODE_WINDOWS: ScheduleMode = "windows"
